name: main

on: [push, pull_request]

jobs:

    build:

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                php: ['7.4', '8.0']
                include:
                    - php: '8.0'
                      composer-options: '--ignore-platform-reqs'

        steps:

            - name: Configure Git
              if: ${{ matrix.os == 'windows-latest' }}
              run: |
                  git config --system core.autocrlf false
                  git config --system core.eol lf

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
              with:
                  php-version: ${{ matrix.php }}
                  extensions: json
                  tools: composer:v2
                  coverage: pcov

            - name: Get Composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}

            - name: Analyze & test
              run: |
                  composer vnd:lint
                  composer vnd:analyze
                  composer vnd:test:coverage:ci -- --coverage-text

            - name: Publish code coverage
              uses: paambaati/codeclimate-action@v2.6.0 # https://github.com/paambaati/codeclimate-action
              with:
                  # Action requires coverageCommand, but we ran it in the previous step.
                  coverageCommand: echo "Sending coverage to Code Climate"
                  coverageLocations: ${{github.workspace}}/build/logs/clover.xml:clover
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              continue-on-error: true
            - name: Codecov
              uses: codecov/codecov-action@v1